export const GET_MOVIELIST_REQUEST = "GET_MOVIELIST_REQUEST";
export const GET_MOVIELIST_SUCCESS = "GET_MOVIELIST_SUCCESS";
export const GET_MOVIELIST_FAIL = "GET_MOVIELIST_FAIL";

export const GET_MOVIEDETAILS_REQUEST = "GET_MOVIEDETAILS_REQUEST";
export const GET_MOVIEDETAILS_SUCCESS = "GET_MOVIEDETAILS_SUCCESS";
export const GET_MOVIEDETAILS_FAIL = "GET_MOVIEDETAILS_FAIL";